require: rubocop-rails
AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case
Metrics/BlockLength:
  Enabled: false